In [20]:
npy_path = '/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/normal/valid/i3d/C_1_1_85_BU_DYB_10-19_13-12-56_CB_DF1_M4_M4.npy'

In [21]:
import numpy as np

# 파일 경로 설정

# .npy 파일 로드
data = np.load(npy_path)

# 데이터 출력
print(data)

[[0.05403253 0.04719771 0.09394115 ... 0.60145062 0.87512392 0.28669068]
 [0.05026708 0.05378525 0.10244136 ... 0.48318315 0.75360364 0.25416008]
 [0.06024395 0.0480429  0.16292186 ... 0.64945054 0.79323584 0.05638819]
 ...
 [0.0962797  0.04572018 0.19400896 ... 0.61382604 0.46847504 0.27175748]
 [0.07065805 0.06776722 0.14306521 ... 0.44982889 0.52573949 0.27433386]
 [0.07579204 0.1174412  0.19322009 ... 0.51436007 0.70264393 0.30521306]]


In [22]:
data.shape

(56, 1024)

In [37]:
norm_i3d = '/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/normal/i3d'
norm_val = '/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/normal/valid/i3d/'
abnorm_i3d = '/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/i3d'
abnorm_val = '/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/valid/i3d'

In [6]:
import os
name_shape = []
folder_path = norm_i3d
# 해당 폴더에 있는 모든 파일들의 이름과 크기를 출력
for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)  # 파일의 전체 경로
    if os.path.isfile(file_path):  # 파일이 맞는지 확인
        data = np.load(file_path)
        name_shape.append((data.shape, file_path))

In [7]:
len(name_shape)

4959

In [8]:
print(name_shape[i][0] for i in range(len(name_shape)))

<generator object <genexpr> at 0x7fe8d19eaf60>


In [9]:
count_37_1024 = sum(1 for shape, name in name_shape if shape == (37, 1024))
count_37_1024

4150

In [10]:
count_37 = 0
count_56 = 0
for shape, name in name_shape :
    if shape ==(37,1024) :
        count_37 += 1 
    elif shape == (56,1024):
        count_56 += 1
    else : print(shape, name)

print(count_37)
print(count_56)

4150
809


In [11]:
for shape, name in name_shape :
    if shape ==(37,1024) :
        print(name)

/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/normal/i3d/C_2_5_35_BU_SYA_09-15_15-29-07_CA_RGB_DF1_M3_M3.npy
/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/normal/i3d/C_2_5_91_BU_SYA_09-16_11-58-02_CC_RGB_DF1_F3_F3.npy
/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/normal/i3d/C_2_5_45_BU_DYA_08-05_14-28-30_CB_RGB_DF1_M3_F3.npy
/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/normal/i3d/C_2_2_26_BU_SMB_10-15_20-52-40_CD_RGB_DF1_F2_F2.npy
/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/normal/i3d/C_2_4_31_BU_SMB_10-16_16-52-07_CD_RGB_DF1_M3_M3.npy
/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/normal/i3d/C_2_5_48_BU_SYB_10-16_14-32-06_CB_RGB_DF1_F3_F3.npy
/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/normal/i3d/C_2_4_8_BU_SYB_10-16_15-39-06_CC_RGB_DF1_F1_F1.npy
/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매

In [14]:
for shape, name in name_shape :
    if shape ==(56,1024) :
        print(name)

/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/normal/valid/i3d/C_1_1_88_BU_DYA_07-18_16-17-30_e_DF1_F2_M2.npy
/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/normal/valid/i3d/C_1_1_85_BU_DYB_10-19_13-12-56_CC_DF1_M4_M4.npy
/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/normal/valid/i3d/C_1_1_90_BU_DYA_07-18_16-30-36_d_DF1_F2_M2.npy
/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/normal/valid/i3d/C_1_1_90_BU_DYA_07-18_16-30-36_a_DF1_F2_M2.npy
/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/normal/valid/i3d/C_1_1_91_BU_DYA_07-18_16-36-43_a_DF1_F2_M2.npy
/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/normal/valid/i3d/C_1_1_89_BU_DYA_07-18_16-24-19_f_DF1_F2_F2.npy
/home/bigdeal/mnt2/238-1.실내(편의점,_매장)_사람_구매행동_데이터/PreProcessToNPY/01.원천데이터/normal/valid/i3d/C_1_1_92_BU_DYA_07-18_16-42-53_a_DF1_F2_F2.npy
/home/bigdeal/mnt2/238-1.실내(편의점,_

In [59]:
import os
name_shape_norm_val = []
folder_path = norm_val
# 해당 폴더에 있는 모든 파일들의 이름과 크기를 출력
for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)  # 파일의 전체 경로
    if os.path.isfile(file_path):  # 파일이 맞는지 확인
        data = np.load(file_path)
        name_shape_norm_val.append((data.shape, file_path))

In [60]:
len(name_shape_norm_val)

620

In [61]:
count_37 = 0
count_56 = 0
for shape, name in name_shape_norm_val :
    if shape ==(37,1024) :
        count_37 += 1 
    elif shape == (56,1024):
        count_56 += 1
    else : print(shape, name)

print(count_37)
print(count_56)

519
101


In [62]:
import os
name_shape_abnorm_i3d = []
folder_path = abnorm_i3d
# 해당 폴더에 있는 모든 파일들의 이름과 크기를 출력
for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)  # 파일의 전체 경로
    if os.path.isfile(file_path):  # 파일이 맞는지 확인
        data = np.load(file_path)
        name_shape_abnorm_i3d.append((data.shape, file_path))

In [63]:
len(abnorm_i3d)

77

In [ ]:
count_11 = 0
count_56 = 0
for shape, name in name_shape_abnorm_i3d :
    if shape ==(11,1024) :
        count_11 += 1 
    elif shape == (56,1024):
        count_56 += 1
    else : print(shape, name)

print(count_11)
print(count_56)

641
0


In [65]:
import os
name_shape_abnorm_val = []
folder_path = abnorm_val
# 해당 폴더에 있는 모든 파일들의 이름과 크기를 출력
for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)  # 파일의 전체 경로
    if os.path.isfile(file_path):  # 파일이 맞는지 확인
        data = np.load(file_path)
        name_shape_abnorm_val.append((data.shape, file_path))

In [66]:
len(name_shape_abnorm_val)

80

In [67]:
count_11 = 0
count_56 = 0
for shape, name in name_shape_abnorm_val :
    if shape ==(11,1024) :
        count_11 += 1 
    elif shape == (56,1024):
        count_56 += 1
    else : print(shape, name)

print(count_11)
print(count_56)

80
0


# npy len

In [5]:
path1 = '/home/bigdeal/mnt2/BN-WVAD/i3d-features/i3d-features/test/A.Beautiful.Mind.2001__#00-25-20_00-29-20_label_A__0.npy'

In [8]:
import numpy as np

data1 = np.load(path)
data1

array([[0.39029422, 0.1425842 , 0.37637228, ..., 1.0082062 , 0.07752518,
        0.03068578],
       [0.50525784, 0.1417145 , 0.25067848, ..., 0.6082658 , 0.14711556,
        0.1033475 ],
       [0.31682354, 0.11912844, 0.1746189 , ..., 0.5465847 , 0.09249274,
        0.07046405],
       ...,
       [0.13181867, 0.19168986, 0.46866274, ..., 0.39425746, 0.3051676 ,
        0.00880623],
       [0.12418692, 0.18669319, 0.5245077 , ..., 0.36978763, 0.38920772,
        0.        ],
       [0.22545709, 0.21978682, 0.6642434 , ..., 0.5914883 , 0.15519458,
        0.        ]], dtype=float32)

In [9]:
data1.shape

(360, 1024)

In [10]:
path2 = '/home/bigdeal/mnt2/BN-WVAD/i3d-features/i3d-features/test/A.Beautiful.Mind.2001__#00-25-20_00-29-20_label_A__1.npy'
data2 = np.load(path2)
data2.shape

(360, 1024)

In [12]:
import os
path_all = '/home/bigdeal/mnt2/BN-WVAD/i3d-features/i3d-features/test'

In [14]:
shapes = []
for filename in os.listdir(path_all):
    file_path = os.path.join(path_all, filename)  # 파일의 전체 경로
    if os.path.isfile(file_path):  # 파일이 맞는지 확인
        data = np.load(file_path)
        shapes.append(data.shape)

In [39]:
sum = 0
for i in range(100) :
    sum += shapes[i][0]

print(sum)
print(sum *40)

19192
767680


In [31]:
num = 0
for i in range(len(shapes)) :
    num += shapes[i][0]


In [32]:
num

728245

In [33]:
len(shapes)

4000